### ISSUE TITLE
No method to close the connect

### ISSUE THREAD

**Issue by hebinbin18** [yookoala/gofast#14]
get := func(path string) (w *httptest.ResponseRecorder, err error) {
		h := php.NewHandler("", "tcp", "127.0.0.1:9000")
		r, err := http.NewRequest("GET", path, nil)
		if err != nil {
			return
		}
		w = httptest.NewRecorder()
		h.ServeHTTP(w, r)

		return
	}

How to close ServeHTTP conn?

**Comment by yookoala** [comment]
It is supposed to be closed within the handler (as it is the "server") and not from outside.
Ideally it should take context deadline and kill automatically.

What do you have in mind?

**Comment by yookoala** [comment]
The issue owner is not specifying enough for the issue. Close for now.

Can re-open if there is more info.

**Comment by yookoala** [comment]
@hebinbin18 Finally see what yo meant.

The Handler.ServeHTTP now closes underlying connection after every requests (see d67b7bf).
There is also new client pooling layer.
