### ISSUE TITLE
gofast is missing some fastcgi fields that Caddy has

### ISSUE THREAD

**Issue by ijt** [yookoala/gofast#27]
Comparing fastcgi.go in the Caddy sources to session.go in gofast, I found the following fields in Caddy that are missing from gofast:

REMOTE_HOST 
REMOTE_USER  
REQUEST_SCHEME 
HTTP_HOST

**Comment by yookoala** [comment]
* `REMOTE_HOST`: requires a DNS lookup for the `REMOTE_ADDR` IP address. I think we should do this as an optional middleware.
* `REMOTE_USER`: I'm not sure I understand what it should be. Do you have more reference?
* `REQUEST_SCHEME`: added in a working branch.
* `HTTP_HOST`: as other `HTTP_*` parameter, it is only available if the request header exists. So if the request header has a `Host` field, it will be passed on as `HTTP_HOST`.

**Comment by yookoala** [comment]
Just read [fastcgi.go](https://github.com/mholt/caddy/blob/master/caddyhttp/fastcgi/fastcgi.go) from [Caddy](https://github.com/mholt/caddy). Turns out they only use IP address for REMOTE_ADDR. No reverse lookup is done. We can follow this practice.

**Comment by yookoala** [comment]
I've done more readings in [StackOverflow](https://stackoverflow.com/questions/4096151/how-reliable-is-http-host) about the HTTP_HOST behavior. All HTTP/1.1 clients will generate the `Host` header, which will become the `HTTP_HOST` parameter. For HTTP/1.0 clients, the `Host` header field will be absent and `HTTP_HOST` parameter is expected to be undefined.

So I don't think the way Caddy doing is the right way to do it.

**Comment by yookoala** [comment]
As for `REMOTE_USER`, it seems the parameter is set by the web server which does HTTP basic authentication, or other authentication applicable.

So the way to support it would be to have a middleware that does HTTP authentication. Caddy has an http.Handler implementation for this as [caddy/basicauth](https://github.com/mholt/caddy/blob/master/caddyhttp/basicauth/).

We'll probably need to do something similar. But this call for a larger and more general question: how should this library support authentication in general?
