### ISSUE TITLE
gofast hangs on error_log() in php script

### ISSUE THREAD

**Issue by ijt** [yookoala/gofast#28]
I made a script like this:

```
$ cat index.php 
<?php error_log('uh oh');
```

When I ran my gofast app with php-fpm on this script, and then hit it with `curl localhost:8081`, it issued the following error and then no longer responded to requests:

```
2018/07/05 03:23:39 gofast: error stream from application process PHP message: uh oh
```

**Comment by yookoala** [comment]
@ijt: I have created [a branch](https://github.com/yookoala/gofast/tree/fix_php_error_stream) to test and fix this, but I cannot reproduce the problem with [this script](https://github.com/yookoala/gofast/blob/7ab09178d788a03309c1e22779052284c702fbb8/example/php/htdocs/error.php). Can you show me the server-side code also? Thanks.

**Comment by ijt** [comment]
I don't understand why you made a different script. Why not use the repro script I provided? It works fine to reproduce the problem. You just have to make another request and it will hang.

**Comment by yookoala** [comment]
I've tried that script, too. Changing the script content doesn't help reproducing the problem on my platform / Travis CI.

**Comment by yookoala** [comment]
I suspect the Go code you used might be related to the issue.

**Comment by ijt** [comment]
Here is a repro case. https://gist.github.com/ijt/dfb2e87087089380f4164ab27991af7c

**Comment by yookoala** [comment]
Thanks. I've found a way to reproduce the issue, along with a possible fix. Please check #36.
