### ISSUE TITLE
Fix writeRequest bug, missing fastcgi_params and several other issues

### ISSUE THREAD

**Issue by yookoala** [yookoala/gofast#7]
@hilyjiang,

Just found your [fork](https://github.com/hilyjiang/gofast) by surprise.

You have fixed several issues in his forked version.
Would be glad to merge the changes if you care to make a pull request :-)

**Comment by hilyjiang** [comment]
Of course. Please refer to #8 .

**Comment by yookoala** [comment]
Merged #9 and fixed this. Thanks @hilyjiang :-)
