### ISSUE TITLE
Content-Type and Content-Length

### ISSUE THREAD

**Issue by farhanz** [yookoala/gofast#72]
In session.go, CONTENT_TYPE and CONTENT_LENGTH environment variables are set (as empty) even if Content-Type and Content-Length request headers are not specified in the original HTTP request. This is likely to cause certain back ends to fail as these env vars would contain empty values. 

Is it possible to set these headers if and only if these are supplied on the request?

**Comment by yookoala** [comment]
If I remember correctly, these are required in the fastcgi specification. I'll consider to change after re-reading the spec.
