### ISSUE TITLE
License issues

### ISSUE THREAD

**Issue by js-sketch** [yookoala/gofast#73]
Hi :-).

I read through your license file and noticed a couple of things:

1. It's spelled "LICENCE" instead of "LICENSE". This can make automatic LICENSE detectors miss your file
2. You (Yeung Shu Hung) share the copyright with "the Go Authors", but aren't you the sole author of this project?
 
It'd be nice if you can change the spelling from "LICENCE" to "LICENSE", as this may make it easier for automatic license detectors to find your license file.

Number 2 isn't a big deal, it's your project and you get to assign copyright to whoever you want of course. I just thought it was curious :-).

Cheers!

**Comment by yookoala** [comment]
Hi @js-sketch,

Thanks for reading about this project. My answers to your comments:

1. Thanks for spotting out. Will change it later.
2. Some of the source code (mainly, fcgi.go) is from the core Go fcgi library. I do not solely own that part of the source code. So I licensed it accordingly.

**Comment by js-sketch** [comment]
>Some of the source code (mainly, fcgi.go) is from the core Go fcgi library. I do not solely own that part of the source code. So I licensed it accordingly.

Ah, cheers! I tried looking into the git log to see if you had clearly copied some code, but I didn't look closely enough apparently.
